### ISSUE TITLE
invisible wall in a cave

### ISSUE THREAD

**Issue by lordbogit** [SWG-Source/dsrc#112]
corillian droid fartory. i know the creen shot due not sow mutch but there is ans invisible was stoping platers form going down but  you can get arroung by walking in to the cave wall
![image](https://user-images.githubusercontent.com/353448/80098459-d382a600-8564-11ea-8707-19f005ba1ae1.png)

**Comment by IrishDarkshadow** [comment]
The cave is located in corellia_1_5

I am able to run in and out of the cave with no issues. I went all the way down to the first room of NPCs and then all the way back out unhindered.

Anyone else have a problem with this one?

**Comment by IrishDarkshadow** [comment]
The problem does not manifest when using the debug client executable. If you use the release executable, the invisible wall can be encountered.

**Comment by IrishDarkshadow** [comment]
Cleared out the clientside buildout for corellia_1_5.iff and still encounter the invisible wall

**Comment by IrishDarkshadow** [comment]
Update from the original reportee:
![image](https://user-images.githubusercontent.com/12293802/85203604-cb49ab80-b306-11ea-92fb-69ee973170e7.png)

Some testing will be required to see what exactly in the cfg files causes the problem but this makes a lot more sense than portal issues in files that were in the client on live for over seven years with no sign of these issues.
