### ISSUE TITLE
DWB doors wont open

### ISSUE THREAD

**Issue by polsommer** [SWG-Source/dsrc#113]
dwb dont wants to let me in tryid all the flaging methods

**Comment by IrishDarkshadow** [comment]
- Went to Jabba's palace
- Spoke to Boba Fett
- Went to DWB
- Tried to enter and got warped back outside as expected
- Clicked on terminal, got access granted message
- Walked into bunker without any problem

Looks like you have a problem with your setup.

**Comment by polsommer** [comment]
its a totaly new setup from ur source mate ?

**Comment by polsommer** [comment]
but could it be the client files ?

**Comment by IrishDarkshadow** [comment]
Tested on QA server running the wod branch using WoD client - no issue

Tested on fresh VM running master branch using stock updated client - no issue
