### ISSUE TITLE
Strings Missing - Empire Day / Remembrance Day

### ISSUE THREAD

**Issue by Namsemag** [SWG-Source/dsrc#115]
![screenShot0107](https://user-images.githubusercontent.com/55237094/80924307-1e2fc980-8d80-11ea-8749-b5af81453ba9.jpg)

**Comment by Namsemag** [comment]
![screenShot0108](https://user-images.githubusercontent.com/55237094/80924343-48818700-8d80-11ea-88d7-381253b05ed3.jpg)

**Comment by Namsemag** [comment]
![screenShot0114](https://user-images.githubusercontent.com/55237094/80924673-2be64e80-8d82-11ea-9524-1015b73924b7.jpg)

**Comment by Namsemag** [comment]
![screenShot0115](https://user-images.githubusercontent.com/55237094/80993818-a4591800-8e33-11ea-96ed-8e88a5989c88.jpg)

**Comment by Cekis** [comment]
Fixed most of these conversations.  I was not able to exhaustively test so please let me know if they're still broken.  You will need to pull latest DSRC and rebuild the Java scripts before testing.
