### ISSUE TITLE
Server Crash When Docking In Space

### ISSUE THREAD

**Issue by sticks2681** [SWG-Source/dsrc#116]
Around April 8 2020 I originally had the server crash when attempting the space quest mission named "Black Sun Infiltration: The Spy". Part of the "Searching for Black Sun" quest from Laetin A'shera on Tansarii.
I was flying the basic starter Scyk given on the station. I followed the mission parameters and as soon as I hit the "U" key to dock, the server crashed. Below is the system message when it occurred:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x08b971d6, pid=3347, tid=3347
#
# JRE version: OpenJDK Runtime Environment (11.0.4+11) (build 11.0.4+11-suse-lp151.3.6.1-i386)
# Java VM: OpenJDK Server VM (11.0.4+11-suse-lp151.3.6.1-i386, mixed mode, tiered, g1 gc, linux-x86)
# Problematic frame:
# C  [SwgGameServer+0xb4f1d6]  AiShipBehaviorDock::AiShipBehaviorDock(ShipController&, ShipObject&, float)+0xf6
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %e" (or dumping to /home/swg/swg-main/exe/linux/core.3347)
#
# An error report file with more information is saved as:
# /home/swg/swg-main/exe/linux/hs_err_pid3347.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Cluster swg is not ready for players.
```
This happened twice in a row (crashed, rebooted server, tried mission again and crashed the second time). At the time I thought I may have done something wrong when updating to the serverdata and after build the VM over from scratch (new characters and all) I completed all the missions on Tansarii with no issues.

On May 4 2020, I began having a similar crash happen.
While doing the space quest mission "Inspect the Nym Lieutenants", the first mission for Commander Oberhaur if the Imperial Pilot Storm Squadron, I disabled the target ship, inspected it, and once again had the server crash as soon as I hit "U" to dock.
This occurred twice in a row while I was flying a crafted Havoc starfighter in which I had modified the game files for mass and to try to allow POB weapons.
I switched to a crafted Heavy TIE and was able to dock and complete the mission with no issues.
I then went back and reverted the mods I had made to the Havoc files, crafted a new Havoc starfighter (although I did use god mode and put the same POB components into the new ship) and again got the crash when attempting to dock.
Finally, I attempted to use the Havoc once more with non-POB components and again got the crash.
Below is the message from the last one:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x08b9a8c6, pid=20947, tid=20947
#
# JRE version: OpenJDK Runtime Environment (11.0.4+11) (build 11.0.4+11-suse-lp151.3.6.1-i386)
# Java VM: OpenJDK Server VM (11.0.4+11-suse-lp151.3.6.1-i386, mixed mode, tiered, g1 gc, linux-x86)
# Problematic frame:
# C  [SwgGameServer+0xb528c6]  AiShipBehaviorDock::AiShipBehaviorDock(ShipController&, ShipObject&, float)+0xf6
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %e" (or dumping to /home/swg/swg-main/exe/linux/core.20947)
#
# An error report file with more information is saved as:
# /home/swg/swg-main/exe/linux/hs_err_pid20947.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Cluster swg is not ready for players.
New chat server connection active
New Game Server connection active
Cluster swg is ready for players.
```
[hs_err_pid3347.log](https://github.com/SWG-Source/dsrc/files/4584689/hs_err_pid3347.log)
[hs_err_pid20947.log](https://github.com/SWG-Source/dsrc/files/4584690/hs_err_pid20947.log)

**Comment by sticks2681** [comment]
As a follow-up, I got to wondering if the crash may for some reason be caused by using a non-Imperial ship while doing an Imperial squadron mission (full disclosure: after completing two of the other squadrons I used /skill grantCommand to give my character all of the pilot certifications, including those for ships from other factions).
I crafted an Ixiyen starfighter and equipped it, game myself the correct mission again using /qatool (mission is spacequest/inspect/imperial_ss_1) and was able to complete it with no issues.
I don't know how to check but I'm wondering if maybe the Havoc is missing something in the docking animation, or possibly the coordinates or whatever are used for when we see the camera pull back and the ship swing around to dock. When the crash happens with the Havoc, the camera never pulls back.

**Comment by sticks2681** [comment]
I tested with a few more ships today with mixed results. All tests were done on the same mission as previously used.
The Jedi Starfighter docked and everything worked correctly. 
Both the T-Wing and TIE Defender caused the same crash as the Havoc in the original post.

**Comment by Namsemag** [comment]
The N1 does it too, seems all "new" ships

**Comment by Cekis** [comment]
I tried this with the original mission you did with a fresh character going through the Tansarii questlines... I docked without issue and the mission completed - no crash.

Now, I am going to close this because I don't think this issue is still around since the fix to the serverdata repo.  If you or anybody else have issues with docking AFTER updating to the latest serverdata AND latest client-assets repos, please re-open or comment on this so somebody else can re-open it.
