### ISSUE TITLE
Itemplacement working incorrect 

### ISSUE THREAD

**Issue by hugoswg** [SWG-Source/dsrc#138]
Problem: If you place anything in a  tatooine small house, it wont align with the floorlevel of the house but the terrain instead. Since the backroom is lower than the frontroom, it does only show, if you look carefully. If you try to move it up or down via radialmenu or command, you get the Message: This is not a valid location.

How to replicate: Place a Small tatooine house and drop something in the front room and back room.

Tested: With crafted house and frog house on both bare metal install and fresh VM on a newly cloned Client.

I also attached some Screens on how it should actually look.

![correcteisley2](https://user-images.githubusercontent.com/69413070/89726432-d96c9c00-da1a-11ea-9fe0-a976e6753731.png)
![correcteisley1](https://user-images.githubusercontent.com/69413070/89726435-db365f80-da1a-11ea-863a-f193fed82eda.png)
![wrongbackroom](https://user-images.githubusercontent.com/69413070/89726433-da053280-da1a-11ea-9976-b57aaacf9a5a.png)
![wrongfrontroom](https://user-images.githubusercontent.com/69413070/89726434-da9dc900-da1a-11ea-97d1-94bd3c2e1f6f.png)

**Comment by hugoswg** [comment]
Same issue appears to happen with every other playerbuilding.

**Comment by hugoswg** [comment]
I tested it further: Seems that the bounding box of the cell is ignored by the placement code. 
It´s not only with craftingstations but every other item you drop in a house. Doesn´t matter if backpack or a chair.
Always same behaviour.

**Comment by AconiteGodOfSWG** [comment]
I can't replicate this. Can anyone else?

**Comment by Cekis** [comment]
I'm also unable to replicate this.  Closing as not reproduceable.
