### ISSUE TITLE
GU 16.0 - Paint Target Usage Issue

### ISSUE THREAD

**Issue by IrishDarkshadow** [SWG-Source/dsrc#140]
Officers
	Paint Target 1-3 (non-expertise) may now be used by all weapons, except heavy. Previously, only pistols and melee weapons could be used.

From GrandMasterVader:

Failed - I test with all weapons and you can use "Paint Target 1-3" skill in mobs including Heavy Weapon.

**Comment by AconiteGodOfSWG** [comment]
I can't replicate this. The commands datatable reflects what is listed here as intended. As indicated in the screenshot below, I have equipped a heavy weapon and it has disabled the Paint Target command.

![image](https://user-images.githubusercontent.com/63141077/97771015-2d18ee00-1b0f-11eb-9aac-642350ff7dfb.png)

**Comment by AlecH92** [comment]
Command table still shows of_deb_def_1 to _3 not blocked by heavy weapons:
https://github.com/SWG-Source/dsrc/blob/master/sku.0/sys.shared/compiled/game/datatables/command/command_table.tab#L334
Line should read like of_deb_def_4 through 8, `ALL	HEAVY`

**Comment by AconiteGodOfSWG** [comment]
Maybe I'm confused about what this report is for. Is `paintTarget` not the command this is referencing? And is that not the skill depicted in the toolbar of my screenshot?

**Comment by AlecH92** [comment]
paintTarget is an old skill, of_deb_def_# is the Paint Target skill granted to Officers. this report references ranks 1 through 3, which are granted via leveling. ranks 4 through 8 are granted by an expertise box

**Comment by AconiteGodOfSWG** [comment]
Ah, I see. Thanks for that clarification!
