### ISSUE TITLE
Instance Stranded

### ISSUE THREAD

**Issue by GrandMasterVader** [SWG-Source/dsrc#142]
I was playing normally and close the client , open it again and the instance never load up.

![WTF](https://user-images.githubusercontent.com/69476485/91648414-55b03900-ea35-11ea-91f0-ba1fcfd618ce.png)

**Comment by Cekis** [comment]
This has been fixed.  You will now be teleported to the tutorial if this situation happens.  Thanks @AlecH92 for your help on this issue and being that soundboard for the ideas on how to fix this!

**Comment by AconiteGodOfSWG** [comment]
fixed via: c3d6e4e
