### ISSUE TITLE
GU 16.9 - No Trade Removable

### ISSUE THREAD

**Issue by GrandMasterVader** [SWG-Source/dsrc#159]
Having item No Trade Shared for example "Hologram of Tatooine" and you open the radial menu, doesn't show the "Make Tradable" option.

![No Tradable Option](https://user-images.githubusercontent.com/69476485/98707780-cc7f8180-2356-11eb-9cec-c8b34dbe5168.png)

**Comment by AconiteGodOfSWG** [comment]
Fixed via swg-source/client-tools@3b794cdcc8
