### ISSUE TITLE
Huj Mat Rug missing

### ISSUE THREAD

**Issue by lordbogit** [SWG-Source/dsrc#164]
Huj Mat Rug is missing off lootsearch
![image](https://user-images.githubusercontent.com/353448/99412474-aa54a900-28ec-11eb-8200-52837aaaccde.png)
https://swg.fandom.com/wiki/Huj_Mat_Rug

**Comment by Erusman** [comment]
The Huj Mat rug info.
appearance = appearance/frn_sc_neutral_rug_s01.apt. 
template =  object/tangible/loot/creature_loot/collections/shared_opt_in_mail_11.tpf
Part of patch_54_client_00 patch_54_shared_00 
static_item_n  = col_mail_opt_in_4_02  Huj Mat Rug
consumable, and part of marketing email collection.

We just need to add it and update master_item datatable etc.
