### ISSUE TITLE
tat Finding huff's rifle no update

### ISSUE THREAD

**Issue by lordbogit** [SWG-Source/dsrc#167]
the mission will not update when bravo the Hutt give you the rifle or a replacement
![image](https://user-images.githubusercontent.com/353448/99433671-b6993000-2905-11eb-8e33-d54b9eb7d7af.png)
![image](https://user-images.githubusercontent.com/353448/99433729-cca6f080-2905-11eb-9bc8-c5359d74225f.png)

**Comment by AconiteGodOfSWG** [comment]
This is not a bug, but agree it's a bit confusing! The quest description says "When you have the rifle, give it to Huff's guard by dragging it on to him." The trigger for completing the quest task is when you drag the rifle onto the guard, not when Borvo gives it to you.
