### ISSUE TITLE
tat Tolan Nokkar appurtenance 

### ISSUE THREAD

**Issue by lordbogit** [SWG-Source/dsrc#168]
server is spawning a human female not a male Sullustan 
![image](https://user-images.githubusercontent.com/353448/99442853-ddf5fa00-2911-11eb-8677-e1112cac854d.png)

**Comment by AconiteGodOfSWG** [comment]
This spawner uses the `fringer` mobile which randomizes the actual appearance template used. While I agree that this doesn't make sense from a lore perspective, it is not a bug because the behavior was the same on live as noted here: https://starwars.fandom.com/wiki/Tolan_Nokkar#Behind_the_scenes
