### ISSUE TITLE
tat Melios Purl mission conversation script

### ISSUE THREAD

**Issue by lordbogit** [SWG-Source/dsrc#171]
another misaligned scripts
![image](https://user-images.githubusercontent.com/353448/99486938-1d960380-295d-11eb-94f6-5390eca3cba2.png)
![image](https://user-images.githubusercontent.com/353448/99487020-503ffc00-295d-11eb-85a4-21887caf099e.png)
![image](https://user-images.githubusercontent.com/353448/99487273-d6f4d900-295d-11eb-87e1-c29679e5f193.png)
![image](https://user-images.githubusercontent.com/353448/99487319-f1c74d80-295d-11eb-81cc-f0b0101f64f3.png)

**Comment by Cekis** [comment]
This needs testing again since a fix was applied.

**Comment by lordbogit** [comment]
working properly good work
