### ISSUE TITLE
Tekil Barje not spawned

### ISSUE THREAD

**Issue by lordbogit** [SWG-Source/dsrc#174]
Tekil Barje is not spawned
![image](https://user-images.githubusercontent.com/353448/99496751-c566fd80-296c-11eb-9e39-7b1ffe6216f1.png)

**Comment by AconiteGodOfSWG** [comment]
Feedback Needed - I've re-added this NPC, however, I'm not sure if it should stay. This NPC is one of the old Static NPCs from Pre-CU that never got upgraded, so it uses deprecated handling throughout for everything. It doesn't even use the ground quests system at all. That being said, the Wiki does not reference that this NPC was removed from the game, but there was lingering code from SOE which disabled its conversation that I had to remove for it to even work.

If it does stay and/or we do decide to restore it, this will need to be refactored. Not necessarily a ton of work, just work to be done. Need feedback on what should be done with this one (and inevitably a few other of the static_npc bunch that will see the same issue).

**Comment by Cekis** [comment]
Looking at the Talk section of Fandom, it looks like SOE removed him:

```
This is as far as I could get at CL 16. I'll be back. --SwordMage 12:06, 20 Sep 2005 (CEST)


Is this quest still available? I showed up at the waypoint & no Tekil Barje :( --Pteague 09:48, June 2, 2010 (UTC)

Just visited Tekil's waypoint to grab a picture and couldn't find him either - looks like he's been removed. --Drekkin 21:21, April 10, 2011 (AEST)
```

**Comment by Cekis** [comment]
My vote is to remove him with the option to add him with fixes in a mocha branch.

**Comment by Cekis** [comment]
@lordbogit what quest line gave you his location?

**Comment by lordbogit** [comment]
none just the wiki https://swg.fandom.com/wiki/Tekil_Barje

**Comment by AconiteGodOfSWG** [comment]
Done. He'll just need to be re-added to the buildout if we want him back.
