### ISSUE TITLE
Vardias Tyne mission conasation 

### ISSUE THREAD

**Issue by lordbogit** [SWG-Source/dsrc#177]
another misaligned script
![image](https://user-images.githubusercontent.com/353448/99552532-03880f80-29b5-11eb-918a-5f69b53424cc.png)
![image](https://user-images.githubusercontent.com/353448/99552671-2d413680-29b5-11eb-9a5b-6cb026809a5b.png)

**Comment by Cekis** [comment]
This needs testing again since a fix was applied.

**Comment by lordbogit** [comment]
its applied the correct response in a chat bubble no chat interaction i whud say its fixed

**Comment by Cekis** [comment]
Closing as fixed per @lordbogit's investigation (sorry I missed this!!)
