### ISSUE TITLE
GU 16.10 - ESB 30th Anniversary Items & Holocron of Destiny

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/dsrc#190]
ESB 30 - Week 4
	Your destiny awaits ... https://swg.fandom.com/wiki/Holocron_of_Destiny

**Comment by AconiteGodOfSWG** [comment]
Merging #193 #194 and #195 here, so everything related to the ESB Celebration is in one place. I'll take care of these.  

Everything referenced here: https://swg.fandom.com/wiki/The_Empire_Strikes_Back_30th_Anniversary_Celebration

**Comment by lordbogit** [comment]
i have tested it since the work has been done i has a server crash that may or may not be related to the holocron just as i answered my second form last question the server died it had only just been rebooted 30 mins before i think further test might be needed on this item

**Comment by lordbogit** [comment]
i have trimed down the output.log to the point it failed
[output.log](https://github.com/SWG-Source/dsrc/files/5574825/output.log)

**Comment by AconiteGodOfSWG** [comment]
This doesn't provide the information needed. Generally whatever is outputted to the console is the information we need as these are all script-related errors. Can you try repeating this with a fresh holocron? You can get another one with the following command:
 `/createStaticItem item_esb_holocron_of_destiny`
