### ISSUE TITLE
GU 16.0 - Space Factional Commands

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/dsrc#196]
Space Factional Commands
	Players can now go Special Forces by using the Special Forces Command

Tested by Sririerac: Doesn´t always work, no Error message in Console or Ingame.

**Comment by AconiteGodOfSWG** [comment]
Not seeing anything that would prevent faction status change in the scripting for the command at [player.player_faction#21](https://github.com/SWG-Source/dsrc/blob/5c2e112349ad24d2f82d943c91e8994c37bd6adb/sku.0/sys.server/compiled/game/script/player/player_faction.java#L21)
