### ISSUE TITLE
Halloween Vendor: Can't Spend Moon Coins

### ISSUE THREAD

**Issue by Spaceguy5** [SWG-Source/dsrc#2]
When trying to buy items with galactic moon coins, the system message "You lack the funds to make that payment" is received. Other vendors (GCW space, chronicles) appear to work.

This issue is present in the script npc.vendor.object_for_sale

When that script is replaced with the old one from Erusman's VM, the Halloween vendor works properly.

**Comment by Cekis** [comment]
Working on this now.  You wouldn't happen to have a stack trace from your logs on this would you?  If not, that's fine, I'll go try to reproduce.

**Comment by nycofox** [comment]
I have the same issue when testing with the Life Day event, can't purchase with coins and get the same message. I can try and reproduce it, which logs would contain the stack trace?

**Comment by Cekis** [comment]
The general server output logs should have it.  The console log itself.  If you see no error then it may not actually be throwing one.  I got derailed, will jump back on in a few hours.

**Comment by Cekis** [comment]
Ok, this has been fixed.  Please get the latest code from Master and see if that fixes the issues.  I tested this against the halloween vendor, but it should work for all other event vendors as well. #

**Comment by nycofox** [comment]
Can confirm this also works with Life Day vendors. Great work!
