### ISSUE TITLE
GU 16.45 - Junk Dealer distance

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/dsrc#212]
Junk Dealer Revamp
	Players should not be able to sell or buy back junk if they walk too far away from the junk dealer or City Recycling Terminals. Obviously the smuggler fence system should ignore distance since it is irrelevant.

**Comment by AconiteGodOfSWG** [comment]
![image](https://user-images.githubusercontent.com/63141077/99977334-7ce77f80-2d72-11eb-9040-65ec9cd24b40.png)

I'm not able to replicate this. I get the correct system message. What Junk Dealer were you talking to?

**Comment by lordbogit** [comment]
sell an item leave the window open and walk away a bit then sell another item with same window open at 30 meters https://www.youtube.com/watch?v=WZwT5DBLW3Q
