### ISSUE TITLE
ent expetise 

### ISSUE THREAD

**Issue by lordbogit** [SWG-Source/dsrc#221]
i have unlimited expertise on my ent
![image](https://user-images.githubusercontent.com/353448/104039295-1a392e80-51ce-11eb-8f3c-9794445893f7.png)

**Comment by AconiteGodOfSWG** [comment]
Expertise is no longer constrained by defaults when god mode is enabled as of swg-source/src@bf419e8197 / swg-source/client-tools@312b1b020f. Using `/setGod off` to turn off god mode will disable the unlimited expertise.
