### ISSUE TITLE
Player Ships - Visuals for components are missing

### ISSUE THREAD

**Issue by IrishDarkshadow** [SWG-Source/dsrc#23]
So far two known examples:  A-Wing and ARC-170
![image](https://user-images.githubusercontent.com/12293802/54628752-10c95a00-4a6e-11e9-839c-2eab4913dc6c.png)

**Comment by IrishDarkshadow** [comment]
I've tested out replacement apt files for the A-Wing and ARC-170 from freshly extracted final day tre files. The problem persists.

**Comment by IrishDarkshadow** [comment]
I replaced the entire file chain for the A-Wing (apt/msh/sht/dds) and the problem persists.

The next thing I tried was using the v3.3 Erusman client and the problem goes away. That client had ILM enabled in live.cfg and uses the old SB path 70 tre files. I enabled ILM on the swgsource client to no effect. I then ported over the patch 70 tre files and set them as the highest entries in live.cfg and the problem persisted.

I'm leaning toward this not being a visual bug per se but instead something datatable related or another configuration file.

**Comment by AlecH92** [comment]
Components are set per ship via 
datatables/space/ship_chassis_namehere.tab
It might be player_awing or just awing

**Comment by IrishDarkshadow** [comment]
ROFL, dammit Elour, if I'd read that comment 30 mins ago I would have saved myself some digging around in the v1.1 client. The solution to the problem was to remove the player_awing and player_arc170 datatables from the client to allow those in the tre files to take over. 

Fix is in this commit: https://github.com/SWG-Source/client-assets/commit/596cb2dd838ff89c44e22df84204875336cbe841

**Comment by AlecH92** [comment]
You probably want to update dsrc sys.shared tab files to match, I am not sure if they are used by the server to determine anything though.

**Comment by seefo** [comment]
Reopening per elour's (@AlecH92) advice. I think we should properly update this file on the server.

**Comment by IrishDarkshadow** [comment]
Tab files fixed using older copies that had not been corrupted. One additional entry added to each to allow the experimental borstel cannon to be mounted on each ship. Pushed updated IFFs to the client repo too.

https://github.com/SWG-Source/dsrc/commit/b417e94d5407ce6b5492e0fb3aeeaeb4eb2a5e92

https://github.com/SWG-Source/client-assets/commit/97e910b7c956924bef459a33e27efd83e62c550b
