### ISSUE TITLE
Test Game Update 16.8 - Pet Revive range/cast time

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/dsrc#242]
Beast Master
	Pet revive now has a max range of 85m however the further you are from your pet when using the ability, the longer the ability will take to revive your pet.

**Comment by Cekis** [comment]
@SWG-Source/qa This was recently fixed by Reedux... please test this out to make sure it's working properly.  Thanks!

**Comment by AconiteGodOfSWG** [comment]
addressed via #240
