### ISSUE TITLE
Character Builder Terminal does not give trader or entertainer heroic jewelry sets

### ISSUE THREAD

**Issue by seefo** [SWG-Source/dsrc#25]
`Entertainer Tradegy` and `Trader Tinkerer's` options on frog don't give jewelry.  

These two sets need to be added to `datatables/skill/character_builder_heroic_jewelry.iff` in order to be given by the frog.

**Comment by TyroneSWG** [comment]
Working on this.

**Comment by Tekaoh** [comment]
After merging [this PR](https://github.com/SWG-Source/dsrc/pull/29), the frog dispenses the trader and entertainer sets, but the set bonuses on the jewelry do not work. This will likely need another pass.

**Comment by TyroneSWG** [comment]
I think I missed something. I'll check it out.

**Comment by Tekaoh** [comment]
One difference that pops out to me is the Unique column in master_item.tab. Those should likely be set to 1. But I don't know if that would make any difference to the set bonuses. Are the set_id's definitely correct?

**Comment by Tekaoh** [comment]
Ah, the sets are not present in https://github.com/TyroneSWG/dsrc/blob/master/sku.0/sys.server/compiled/game/datatables/item/item_sets.tab

**Comment by Tekaoh** [comment]
The item descriptions could also have the set bonus explanations added like with the other sets.

**Comment by Tekaoh** [comment]
Well, the bonus set explanations appeared after a reboot, so nevermind. The set bonuses work now and the frog worked already, so I'll call this closed. @TyroneSWG Thanks for the PR!
