### ISSUE TITLE
Client Crash on Tutorial after first cutscene

### ISSUE THREAD

**Issue by Janderasm86** [SWG-Source/dsrc#267]
See below for the Log.

Limited Galaxies.exe: unknown.0
c:\git\swg\src\engine\client\library\clientuserinterface\src\shared\core\cuimediator.cpp(1487) : FATAL 3a8ab9d0: Unable to find CodeData property 'buttonEnterSpace' from [/HudSpace] for [SwgCuiHud]

  c:\git\swg\src\external\3rd\library\ui\src\shared\uicomposite.cpp(99) : caller 1
  unknown(0x102C0072) : caller 2
c:\git\swg\src\engine\shared\library\sharedfoundation\src\win32\setupsharedfoundation.cpp(156) : FATAL be5fbc55: ExceptionHandler invoked
  unknown(0x7577CAF0) : caller 1
  unknown(0x773E2824) : caller 2
  unknown(0x773A8914) : caller 3

**Comment by Cekis** [comment]
We just figured this out in discord... this is happening because the client-assets on their machines were out of sync with the client-tools repo.
