### ISSUE TITLE
3 Assault Trooper (Shock) Battle Worn Armor Pieces Not Equipping 

### ISSUE THREAD

**Issue by DevilFangs** [SWG-Source/dsrc#272]
The battle worn variant chest, legs, & boots do not equip.
They do Appearance Equip, but simply do not respond to the actual equip.
Tested on two characters that were both flagged as Combatant & changed to Special Forces as well.

![screenShot0012](https://user-images.githubusercontent.com/79380880/108612825-4b9a4200-73a9-11eb-977b-b0ef6d4a5e76.jpg)

![screenShot0013](https://user-images.githubusercontent.com/79380880/108612828-505ef600-73a9-11eb-808c-94a7267daed1.jpg)

![screenShot0014](https://user-images.githubusercontent.com/79380880/108612830-53f27d00-73a9-11eb-8ccb-010c2433c7d9.jpg)

**Comment by AconiteX** [comment]
Fixed via 7d7437b95d and now pushed to client.
