### ISSUE TITLE
Smuggler Pilot Mission 3

### ISSUE THREAD

**Issue by sririerac** [SWG-Source/dsrc#28]
it´s the mission you´ve to escort and defend a freighter.

You start the mission with a 2-3 waypoints. at the last the freighter appears and the escort part starts. 
After a while, the first wave of Darksun´s will spawn.
You get the Enemy down to 0% Shield, 1% hull, 81% systems but it wont explode. When it should explode it bugs out, 
AI stops working for space
Server goes into not ready and it takes about 3 minutes on this machine for it to be ready again
You can´t Homeport
You can´t hyperspace out
You can only logout and relogin

[hs_err_pid12715.log](https://github.com/SWG-Source/SWG-Source.github.io/files/3034905/hs_err_pid12715.log)

this is the latest error log.

**Comment by IrishDarkshadow** [comment]
The issue was seemingly related to complications from porting the VM over to a physical machine. It has not been possible to recreate the situation within the VM and the mission is working as intended.
