### ISSUE TITLE
GU 20.0 - GCW - Factional Base GCW

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/dsrc#289]
GCW:
	- The amount of GCW earned when a factional base is destroyed will be reduced for each extra player, if more than eight players are eligible for the reward. For example if a group of players are destroying a base worth 2000 GCW points and there are 1-8 players eligible to receive the reward each will get the full 2000. If there's 10, each will get ((2000*8/10) = 1600.

**Comment by AconiteX** [comment]
Implemented via 04a32e3e
