### ISSUE TITLE
GU 17.2 - GCW - Factional Base

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/dsrc#290]
Player Placed Factional Base
	- All player placed factional bases are now displayed under a new Player Placed Factional Base node/category on the Planetary Map that's visible to everyone. Remember, for PvP bases, the Active (sun) / Inactive (moon) icon before the base name indicates whether or not the PvP base is currently in its vulnerability state (Active/sun) or not (Inactive/moon).

**Comment by AconiteX** [comment]
Implemented via 04a32e3e
