### ISSUE TITLE
GU 17.2 - GCW - Contribution Window Display

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/dsrc#292]
Player Placed Factional Base
	- All GCW score contributions (including Factional Presence) made by the character occurring within range of a same-faction base will receive a bonus per base. The War Terminal/War Intel Pad/War Table GCW Personal Contribution window displays the bonus that you would receive at your current location. The bonus and range for each base type are as follows.
		- Forward Outpost - 1%, 750m
		- SF Forward Outpost - 2%, 750m
		- Field Hospital - 3%, 1000m
		- SF Field Hospital - 5%, 1000m
		- Tactical Center - 6%, 1250m
		- SF Tactical Center - 8%, 1250m
		- Detachment Headquarters - 10%, 1500m
		- SF Detachment Headquarters - 12%, 1500m

**Comment by AconiteX** [comment]
Implemented via 04a32e3

**Comment by AconiteX** [comment]
and ebd13f15*
