### ISSUE TITLE
Kaadara Imperial script throwing errors

### ISSUE THREAD

**Issue by Cekis** [SWG-Source/dsrc#3]
On startup, the Kaadara Imperial spawner script is failing to spawn "stuff" in the building... 

```
Unable to get cell id of room (mainhall) in building 1260047 while looking in datatable "datatables/spawning/script_spawner/naboo/kaadara_imperial.iff".
Script is currently attached to OBJID 1741552
script.internal_script_exception: [script bug] JavaLibrary::getCellId passed invalid object
	at script.base_class._getCellId(Native Method)
	at script.base_class.getCellId(base_class.java:7583)
	at script.theme_park.script_spawner.spawner_methods.gcw_spawner.spawnActor(gcw_spawner.java:165)
	at script.theme_park.script_spawner.spawner_methods.gcw_spawner.beginSpawn(gcw_spawner.java:124)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at script.script_entry.callMessageHandler(script_entry.java:745)
	at script.script_entry.callMessageHandlers(script_entry.java:954)
	at script.script_entry.callMessageHandlers(script_entry.java:875)

```

**Comment by AlecH92** [comment]
![image](https://user-images.githubusercontent.com/3212485/51874893-9f93e300-2317-11e9-91da-84d026f47028.png)
as discussed in Discord, my quick fix for this was just adding a delay before it starts to populate areas (is there a certain trigger we can use, on galaxy ready or something along those lines? where does it generate the "cluster is ready for players" message? perhaps attaching to that, and starting the spawn when that is received is a better alternative)

**Comment by Cekis** [comment]
Ok, after looking into this, I see two ways that this can be fixed... the first way is how you suggested and just add an arbitrary time to "wait" expecting everything to be spawned at that point.  The second way would be to re-write the datatables and code to spawn not globally, but by building (the world would be the "base" and each building would have a separate spawner).  The first method is obviously the easiest, but the second method is likely the better way to handle things in the long run.

**Comment by Cekis** [comment]
Looked into your "cluster is ready for players" trigger... there's an "OnPreloadComplete" method that we can implement.  I'm not sure when specifically that gets triggered yet, but it looks promising.  Will keep digging into it.

**Comment by Cekis** [comment]
Ok, this is a good learning... if you create a method, "OnPreloadComplete" (look in the code for examples), it will be called if and ONLY IF you first do a "requestPreloadCompleteTrigger(self)" in the same script.  This means that we can tell the server to do it's preload and put a requestPreloadCompleteTrigger() call in the OnAttach() method.  We also need to add the OnPreloadComplete method to this spawn script that in turn fires off the spawning process.  This should ensure all buildings/cells are spawned by the time the script should run.  I'll implement now and you can see what I did to possibly duplicate for other things.  This would also work great for holiday spawners.
