### ISSUE TITLE
G9 Rigger ITV - doesn't save travel locations

### ISSUE THREAD

**Issue by IrishDarkshadow** [SWG-Source/dsrc#30]
https://cdn.discordapp.com/attachments/433006120295071786/567850154317840399/unknown.png

call itv
save location
travel elsewhere
call itv
choose saved location
get error shown in pic

**Comment by AlecH92** [comment]
String id in your picture is "corrupt_itv_location_data"

Locations in scripts that appears:
./systems/tcg/tcg_instant_travel.java:324:            sendSystemMessage(player, new string_id("tcg", "corrupt_itv_location_data"));
./terminal/terminal_travel_instant.java:225:                sendSystemMessage(player, new string_id("tcg", "corrupt_itv_location_data"));
./terminal/terminal_travel_instant.java:235:                sendSystemMessage(player, new string_id("tcg", "corrupt_itv_location_data"));

I would check out tcg_instant_travel, it's looking for some objvars:
if (hasObjVar(itv, ("travel_tcg.stationary_itv.location." + idx)) && hasObjVar(itv, ("travel_tcg.stationary_itv.scene." + idx)))
Just guessing that the objvar isn't being applied to the ITV correctly - the same objvars are stored on the character I believe.

**Comment by TyroneSWG** [comment]
Isn't this the same type of ITV as the at-at head?

**Comment by Cekis** [comment]
Fixed.
