### ISSUE TITLE
Guild and City Waypoint Buttons in Datapad UI Showing String Data

### ISSUE THREAD

**Issue by bacchus506** [SWG-Source/dsrc#317]
Guild and City Waypoint Buttons in Datapad UI Showing String Data

**Comment by Erusman** [comment]
This was fixed with c[11ed9c4](https://github.com/SWG-Source/client-assets/commit/11ed9c4c1d78cccb4528b0612e5aa7ff7b360929)
We will still need to go in and add functionality to the buttons for Guild and City Waypoints.
