### ISSUE TITLE
createHourlyAlarmClock - cannot find symbol

### ISSUE THREAD

**Issue by BubbaJoeX** [SWG-Source/dsrc#337]
![image](https://user-images.githubusercontent.com/89060381/136675127-b8887c9c-1023-44e3-bc23-37c9dd8e5410.png)

**Comment by BubbaJoeX** [comment]
Wrong branch.

**Comment by langelusse** [comment]
"You made a mistake with the directory. The commands should be typed in the swg_main. For me, there's no issue with compilation."

**Comment by AconiteX** [comment]
this isn't an issue

As context, alarm clock methods were renamed on the 3.1 branch as part of the scripting cleanup and logical name usage improvement initiatives, which would create this error in some cases

No need to respond, issue is closed
