### ISSUE TITLE
GU 18.1 -  Cunning of Tyranus crystal

### ISSUE THREAD

**Issue by IrishDarkshadow** [SWG-Source/dsrc#34]
Rare Loot System
	- A saber with a Cunning of Tyranus crystal will now display its damage and element correctly after adding pearls.

**Comment by IrishDarkshadow** [comment]
![image](https://user-images.githubusercontent.com/12293802/57290585-a5872600-70b5-11e9-8149-e26e957f3b3f.png)
![image](https://user-images.githubusercontent.com/12293802/57290607-ad46ca80-70b5-11e9-858f-f1f667cc5384.png)

**Comment by Cekis** [comment]
Fixed... was a stupid range bug when looking at saber stats.  Somebody didn't check ranges properly.

**Comment by IrishDarkshadow** [comment]
The test for the saber colouring has been restored.
