### ISSUE TITLE
install.sh errors 

### ISSUE THREAD

**Issue by jay-76** [SWG-Source/dsrc#377]
while following the guide for 3.0.2 the install errors,with the following text
`swg@swg:~> ./install.sh
fallocate: fallocate failed: Text file busy
mkswap: error: /swapfile is mounted; will not make swapspace
swapon: /swapfile: swapon failed: Device or resource busy
fatal: destination path 'swg-main' already exists and is not an empty directory.
Buildfile: /home/swg/swg-main/build.xml

clean_src:
     [echo] Cleaning the SRC build directory.
   [delete] Deleting directory /home/swg/swg-main/build

clean_dsrc:
     [echo] Cleaning the DSRC directory.

init:
    [mkdir] Created dir: /home/swg/swg-main/build

clean:

git_update_submods:
     [echo] git submodule
     [exec] error: Your local changes to the following files would be overwritten by checkout:
     [exec] 	linux/localOptions.cfg
     [exec] 	linux/servercommon.cfg
     [exec] Please commit your changes or stash them before you switch branches.
     [exec] Aborting
     [exec] fatal: Unable to checkout 'be961fca467e97b859aaf99d11127212e994c2c7' in submodule path 'exe'

BUILD FAILED
/home/swg/swg-main/build.xml:192: The following error occurred while executing this line:
/home/swg/swg-main/git_targets.xml:116: The following error occurred while executing this line:
/home/swg/swg-main/git_targets.xml:12: exec returned: 1

Total time: 0 seconds
swg@swg:~> cat /proc/swaps
Filename				Type		Size	Used	Priority
/swapfile         `

the last part was just to check whatever accesses,the swapfile
i used the vm, just changed the network id, and ram to 32gb (i have 128 in that pc)

also tried a snapshot, and then a master download,and copy/paste that into the folder.. same result

**Comment by AconiteX** [comment]
This isn't a bug with SWG Source, it is with the environment/virtual machine and likely user error. You can join our Discord for assistance with troubleshooting.
