### ISSUE TITLE
Map is not correctly creating way point when creating way point by right clicking

### ISSUE THREAD

**Issue by edgewoodnm** [SWG-Source/dsrc#380]
Map is not correctly creating way point when creating way point by right clicking.
![Bugreport](https://github.com/user-attachments/assets/fa2928ef-dc58-4f2e-99b5-cffd2fa5b593)

**Comment by AconiteX** [comment]
This is due to the HD/4K/8K maps installed in the client pictured and is not a native source bug.

**Comment by edgewoodnm** [comment]
You are correct Boss man I tried it on my old bucket laptop. You are the Godfather of the 
galaxy =)
