### ISSUE TITLE
Naked toon in starter tuitorial

### ISSUE THREAD

**Issue by Bandit42** [SWG-Source/dsrc#39]
While starting in the new player tutorial on then beginning station, my toon has appeared "naked" with no clothes and no hair. Also noticed in the Terminator window for the server a couple of errors

UPDATE: I just logged back in (no server restart) and now my toon has the basic clothes on when it had no clothes on before after creating toon

![swgsource1](https://user-images.githubusercontent.com/35357152/58134891-23cae880-7bdd-11e9-86e0-e8b5f819615c.jpg)

![swgsource2](https://user-images.githubusercontent.com/35357152/58134904-35ac8b80-7bdd-11e9-9ead-5b202e7f1211.jpg)

**Comment by Tekaoh** [comment]
Looks like this is the same issue as https://github.com/SWG-Source/src/issues/3
