### ISSUE TITLE
Armor and Vehicle color kits don't work

### ISSUE THREAD

**Issue by Zethie** [SWG-Source/dsrc#4]
1. Vehicle color kit does not work (bject/tangible/item/vehicle_customization.iff)
2. Crafted Armor Color kit doesn't work (object/tangible/item/crafted_armor_recolor_kit.iff)

**Comment by seefo** [comment]
above reference is an accident

**Comment by IrishDarkshadow** [comment]
Confirmed on v1.2.1 server and client.

When you try to customise the colour of a vehicle, you get the color window but the selection area shows no colour options and the left pane shows a solid yellow block.

**Comment by IrishDarkshadow** [comment]
I've tried this on a few speeders now and the only one that isn't working so far is the USV-5
![image](https://user-images.githubusercontent.com/12293802/54547186-291d7400-499d-11e9-941a-453088da8f0c.png)

**Comment by IrishDarkshadow** [comment]
Armour recolour kits only work on crafted armour. 
![image](https://user-images.githubusercontent.com/12293802/54549279-a0ed9d80-49a1-11e9-858f-cb9a23e49ac7.png)

Some items when spawned using /object spawn do not arrive with their scripts attached, you would need to either craft them manually (as I did for this test) or use /createStatic Item <static name> if the item has an entry in master_item.tab
