### ISSUE TITLE
God Mode - City Cheats Menu Not Applying Cheats

### ISSUE THREAD

**Issue by IrishDarkshadow** [SWG-Source/dsrc#43]
MrConns reported this as follows: 

"MrConns  Today at 11:33
I've just been messing about with making a player city and I've noticed that there is no update timer shown in chat when clicking the maintenance report, force rank up isn't working and the citizen report is showing Location/Last Login as Offline ????d:??h:??m:??s."

So three issues in there:
(1) no update timer shown in chat when clicking the maintenance report
(2) god mode - force rank up not working
(3) citizenship report shows location/last login as offline

Testing Results:
(1) confirmed but I'm not sure it ever did that....needs further investigation

(2) confirmed... force update / force rank up seem to run but have no effect. I upped a city to 5 residents to test the force update and nothing happened.

(3) This was working fine for me and in the last test showed data for 3 offline and 2 online citizens

**Comment by Tekaoh** [comment]
@IrishDarkshadow Silly question, but you were in god mode when you tried force rank up/down? That for sure worked for me last time I used it. Might have been pre-java 11 though. I can try testing it later...

**Comment by IrishDarkshadow** [comment]
LOL, the menu doesn't show up unless you are in god mode.

**Comment by Tekaoh** [comment]
Good point... Ok, this will be worth looking into I think. This definitely _did_ work, so something must have happened.

**Comment by IrishDarkshadow** [comment]
Agreed, I used these at one point on v1.2.1 to set up a large player city so I could do dev work on the player road system, so I'm heavily leaning towards the Java update on this one.

**Comment by Tekaoh** [comment]
Tested this again on my own server and it seems to work fine for me...

**Comment by IrishDarkshadow** [comment]
Identified as being due to an artifact issue with the Oracle database in the v2.1 VM. Dropping the database and recreating it using ANT commands solves it. It is not present in the released version of the v2.2 VM.
