### ISSUE TITLE
Files with null appearance references

### ISSUE THREAD

**Issue by IrishDarkshadow** [SWG-Source/dsrc#47]
Edit by Tekaoh:
There was a time where unclickable objects were "fixed" by removing their appearanceFilename entries. This was fine for a while but caused a bunch of objects to become invisible when we synced the server to a final day client. Seefo has since added a skipLosCheck option as a better way to fix unclickable objects. This cleanup task involves restoring the appearanceFilename references on the server (and client) and adding skipLosCheck instead if needed.

The following 55 objects are affected: (some others were affected but were already restored)

====================

dsrc\sku.0\sys.shared\compiled\game\object\static\structure\dantooine\shared_dant_fire_pit.tpf
dsrc\sku.0\sys.shared\compiled\game\object\static\structure\dantooine\shared_dant_large_rock_hut.tpf
dsrc\sku.0\sys.shared\compiled\game\object\static\structure\dathomir\shared_mtn_clan_pillar_s01.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_datapad_01.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_datapad_02.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_datapad_03.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_datapad_04.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_datapad_05.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_datapad_06.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_datapad_07.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_datapad_08.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_datapad_09.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rare_rifle_coynite_disruptor.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_bubbling_01.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_bubbling_02.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_bubbling_03.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_bubbling_04.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_bubbling_05.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_bubbling_06.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_bubbling_07.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_bubbling_08.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_bubbling_09.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_bubbling_10.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_burning_01.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_burning_02.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_burning_03.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_burning_04.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_burning_05.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_burning_06.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_burning_07.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_burning_08.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_burning_09.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_burning_10.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_glowing_01.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_glowing_02.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_glowing_03.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_glowing_04.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_glowing_05.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_glowing_06.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_glowing_07.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_glowing_08.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_glowing_09.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_glowing_10.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_steaming_01.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_steaming_02.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_steaming_03.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_steaming_04.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_steaming_05.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_steaming_06.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_steaming_07.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_steaming_08.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_steaming_09.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\collection\shared_rock_steaming_10.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\quest\shared_dead_forest_stump.tpf
dsrc\sku.0\sys.shared\compiled\game\object\tangible\quest\shared_som_burning_marker_04.tpf

**Comment by Tekaoh** [comment]
So digging a little deeper, at least some of these had null apt references at the initial dsrc commit and even in the final day tres. So there's nothing to restore there. I'll have to go through and compare the final day tres to see which (if any) objects even had an apt reference to begin with, then work out why it was removed, then see if it can be put back and maybe solved with a skipLosCheck instead.

**Comment by Tekaoh** [comment]
appearanceFilename has been restored to these files and corresponding files have been removed from client-assets in order to fall back to the final day tres. Each file will need to be checked to make sure that it is indeed visible (it should be) and, more importantly, that it can be interacted with as expected. Any objects with an interaction problem might need a skipLosCheck.

**Comment by Tekaoh** [comment]
QA'ed and approved
