### ISSUE TITLE
Yavin IV Space Duty Missions (Neutral)

### ISSUE THREAD

**Issue by mrmacphisto6595** [SWG-Source/dsrc#51]
Presented with the following options from the spaceport NPC for mercenary missions:

1. Transmitting mission data. Good hunting
2. I'll hunt down tier 3 Black Sun Pirates
3. I'll hunt down tier 3 Void Wing Pirates

Option 1, gives the black sun duty mission.  Option 2 gives the void wing pirates mission.  Option 3 does nothing, but take you back to the main conversation options.

Additionally, if I am not mistaken, the neutral space duty missions for Corellia, list all 3 options as Transmitting mission data. Good hunting.  And I believe it was the second option that gives the black sun duty mission.

**Comment by IrishDarkshadow** [comment]
Those missions are all GU 16 additions. They are currently in testing for issues just like that....string problems.
https://docs.google.com/spreadsheets/d/1DGxJeXRZZFvXK4VRHtFKWDYgTmIrqz9dUvBZEOLzDNI/edit?usp=sharing

**Comment by mrmacphisto6595** [comment]
Gotcha.  Apologies, don't know what I should post and what I shouldn't.  Definitely do not want to create more work, by posting stuff you already know about.

**Comment by IrishDarkshadow** [comment]
Feel free to post any bugs you spot, if it's not on this list already then it's something we need to know about. I just wanted to show you that you're essentially done QA testing if you are doing these missions right now. 

The core issue is that there was an update by SOE to the conversation options the space stations have for these missions that took place post GU 16.4 and as we're using final day strings that causes the conversation options to be "misaligned". I should have them all deal with before the weekend is over.

**Comment by Cekis** [comment]
This should now be fixed.
