### ISSUE TITLE
Mos Eisley Police Officer spawn issue

### ISSUE THREAD

**Issue by Bandit42** [SWG-Source/dsrc#53]
i know this has been a bug for quite awhile but i think i was able see more of what it does to help the devs narrow it down possibly:

ok. noticed something with the random mos eisly police officer spawning on my toon. after i am "stopped" and "searched" thats when it starts to randomly spawn on my toon when i moved by the cantina. then i continue to the garage near the cantina and it doesnt spawn. Then I go back my the spaceport where I was scanned at and the MEPO has disappeared and not standing with the stormtrooper and cannot be found walking around

**Comment by Cekis** [comment]
This was caused by the AI placing a "follow" obj var on the player and never actually removing it after the search was completed.
