### ISSUE TITLE
TCG Barn Issue with recovering stored beasts

### ISSUE THREAD

**Issue by Namsemag** [SWG-Source/dsrc#54]
Certain beasts can't be recovered once stored, issue first discovered with a Horned Raptor but seems mutated beasts are effected.
The beasts ARE stored as you cannot destroy the building as it knows there are beasts stored.

**Comment by Namsemag** [comment]
Steps to reproduce:

1. Place a TCG Barn Structure.
2. Place a Beast of your choosing into the barn, you can let it wander or not, doesn't matter.
3. Have another beast still in your Datapad.
4. Try and retrieve the beast from the structure.

At this point I have no option to retrieve a pet only to store more.

If I then store all beasts from my datapad into the barn I can then retrieve any and all pets.

**Comment by Cekis** [comment]
Let me know when you're available in discord.

**Comment by Cekis** [comment]
Ohhh... I see what the issue is - it's "you have to store all beasts to get just one (or all) out".  Ok, working to fix it now.

**Comment by Cekis** [comment]
Fixed... the ranch hand conversation bailed if it saw you had pets.  Made it so the conversation gives you all realistic options before bailing.  You can now store or retrieve pets without this requirement.
