### ISSUE TITLE
Progresspercentage in GCW window not shown properly

### ISSUE THREAD

**Issue by sririerac** [SWG-Source/dsrc#62]
There are no numbers shown after the dot. only the first 2 digits as seen in the screenshot.
Tried with 3 different toons, all the same outcome.

![gcw](https://user-images.githubusercontent.com/49203967/67154913-01f89d80-f304-11e9-8e96-4aa106d3b36c.PNG)

**Comment by Cekis** [comment]
I'm not liking the layout... I think this might have something to do with your resolution?  Are you running 4k?

**Comment by Tekaoh** [comment]
Looks fine for me. I'm using a 1366x768 resolution, which is pretty typical to swg era.

![screenShot0004](https://user-images.githubusercontent.com/45337851/75280938-59d87100-57dc-11ea-85b6-d8b6c2265790.jpg)

I don't think this is a dsrc issue, so I'm going to close this out for now.
