### ISSUE TITLE
Unable to sell looted backpacks

### ISSUE THREAD

**Issue by sririerac** [SWG-Source/dsrc#63]
When you try to sell looted backpacks you get the confirmation that it has been sold, but at the same point you get the message that the item is to bulky to fit into this container.

After you try to sell the same pack again, you get : <ITEMNAME> is already in the process of being sold....

In order to ge rid of it you eiter need to drop it or destroy it.

![error1](https://user-images.githubusercontent.com/49203967/67156141-1dbb6e00-f31b-11e9-878e-128591527e87.PNG)
![error2](https://user-images.githubusercontent.com/49203967/67156147-214ef500-f31b-11e9-81f2-c167a2ae87de.PNG)

**Comment by Cekis** [comment]
This should now be resolved... please test.
