### ISSUE TITLE
GU 17.8

### ISSUE THREAD

**Issue by IrishDarkshadow** [SWG-Source/dsrc#67]
Miscellaneous
	- Players will no longer be penalized for failing their first attempt at the Rescue the Lok Revenant quest of Nym's Themepark.

**Comment by Cekis** [comment]
Define "penalized".  I've attempted this quest, first left the prisoner behind (got too far from him while escorting), then on the next try let him die - each time the quest simply reset.  On the third try, I escorted him to the waypoint where he was picked up - regardless how far away I was.  Not sure what to fix here.

**Comment by IrishDarkshadow** [comment]
We don't have anything more to go on with this one beyond the SOE patch note saying "penalized" for "failing their first attempt".  

Is there a cooldown timer or something to that effect that gets applied in the current code for this specific quest that we're using? Were you running the quest in god mode?

The patch note comes from GU 17.8 and we know our codebase is GU 16.4 for the most part (prior to other restorations). So whatever SOE did here is something we should by all rights be missing from our code.

**Comment by Cekis** [comment]
Closing then.
