### ISSUE TITLE
Restore: 81 / 84 / 87 / 90 Month Vet Rewards

### ISSUE THREAD

**Issue by IrishDarkshadow** [SWG-Source/dsrc#70]
~~81 Month:~~
- Neural Recon Network Terminal
[item_vet_reward_lockout_remover]
<object/tangible/veteran_reward/data_terminal_s3.iff>
{item.instance_reset}

>> ~~added to master_item~~
>> ~~added to claim window for month 81~~
>> ~~functionality to clear instance lockouts added~~
>> ~~cooldown timer for 2 days needs to be added~~

~~84 Month:~~
~~- Star Destroyer System Console [item_vet_reward_sd_console_01]<object/tangible/furniture/technical/sd_console_s01.iff>
- Star Destroyer Console Row [item_vet_reward_sd_console_02] <object/tangible/furniture/technical/sd_console_s02.iff>~~

>> ~~strings added~~
>> ~~objects added~~
>> ~~needs to be added to master_item.tab~~
>> ~~needs to be added to vet rewards~~

~~87 Month:~~
~~- Respec Reset Device~~
~~[vet_reward_respec_reset]~~

~~90 Month:~~
- Resource Supply Generator
[vet_reward_resource_crate]

**Comment by Cekis** [comment]
Completed - needs review.
