### ISSUE TITLE
Restuss Bug: Galactic Information Broker Multiplies on Server Restart

### ISSUE THREAD

**Issue by Namsemag** [SWG-Source/dsrc#74]
The galactic information broker (Bothian in a hooded robe) located outside the major star ports spawns each time the server is booted regardless if he is there already so it is possible to end up with multiple Bothans in a single location.

**Comment by Cekis** [comment]
This is likely easily fixed, but I need more info on which NPC it is.  The galactic information broker just isn't enough to go off of.  Can you provide a screenshot with location information?

**Comment by Namsemag** [comment]
Sure, its the Bothian guy sat outside all major star ports, here a photo of him in Eisley
![screenShot0041](https://user-images.githubusercontent.com/55237094/75342832-1a1e9180-588f-11ea-923b-f3748aa5f57c.jpg)

**Comment by Cekis** [comment]
Ok... grab that dude's QA Tool info and attach it.  I don't have him on my dev server so he's being spawned by something in game (i.e. Restuss phase or certain options enabled).  To get that info, select the character (not the patrol point he's actually sitting on top of) and do this:

/qatool target

You'll get a window that pops up... either save that info to a file and post it here or screenshot it and post it here.  I'm looking for what he's being spawned by, his object id, his spawn location, his spawner information, his parent, etc.

**Comment by Namsemag** [comment]
![screenShot0062](https://user-images.githubusercontent.com/55237094/75378189-2aecf880-58cb-11ea-9c56-a0f9d67f3b72.jpg)

**Comment by Cekis** [comment]
Nice!  That is perfect... thanks!  I'll take a look at why he's persisting.  Interesting that the patrol waypoint is spawning him, lol... they're usually benign objects!

**Comment by Cekis** [comment]
First review shows that he should be spawning once.  However, if you can check to see if he spawns ONCE PER RESTART of your server then that would be helpful too.  Are you seeing more than two?

This has to do with the fact that you have Restuss starting in Phase 2 as well.  Not sure if the Restuss work I did on the re-do is causing this, but it may be.  What would cause this is if you started Phase 2, then re-started Phase 2 again before rebooting.  This is a side-effect of giving control over Restuss like that.  Will have to put in a check to make sure we are in Phase two or not and despawn if not.

**Comment by Namsemag** [comment]
Currently in Phase 3 of restuss (jumped straight to phase 3), used the restussevent true to turn it on, 2 immediately spawned, on a restart you get more spawns.

This also happens in bestine (where I currently have 3 spawned) theed, etc etc 

Restarted the server and now have more of the little guys

**Comment by Cekis** [comment]
Will take a look when I get a chance... this info helps a ton!

**Comment by Cekis** [comment]
Ok, first issue is that there were two Restuss Brokers being spawned when entering stage 3.  There's still another issue where the brokers should be despawned if going directly to stage 3.  Right now I think they are, but it's going to take 7200 seconds from startup to do so.

**Comment by Cekis** [comment]
Ok, first issue is that there were two Restuss Brokers being spawned when entering stage 3.  There's still another issue where the brokers should be despawned if going directly to stage 3.  Right now I think they are, but it's going to take 7200 seconds from startup to do so.

**Comment by Cekis** [comment]
Ok, Galactic Information Brokers are not supposed to spawn if going into Stage 3.  They're supposed to announce a pending issue in Restuss so they were despawned when the Restuss final stage started (on live).  Because of this, you will only see them spawn if you start up in Stage 2 (config setting of "1" for phase).  If you have the event progression on, you will see things play out as they were supposed to.  If you have it off, they will simply be spawned and will be conversable telling you something fishy is going on in Restuss.
Make sure you get latest from the repository and be sure to recompile the Java and the TABs.  ('ant compile_java' and 'ant compile_tab') to get this fix.
