### ISSUE TITLE
Missing Imperial Mission Terminal at Emperors Retreat, Naboo

### ISSUE THREAD

**Issue by Namsemag** [SWG-Source/dsrc#75]
![screenShot0055](https://user-images.githubusercontent.com/55237094/71312864-4b5e8980-2428-11ea-871b-97c0bb41291d.jpg)

**Comment by Cekis** [comment]
Are you sure this is not located IN the emperor's retreat downstairs and you're just able to target it?  I'm not sure why this happens, but I believe it has something to do with target-able items within a building and no line of sight prevention.

**Comment by Namsemag** [comment]
You can select it from multiple angles etc and it seems like it's in the location on the screen (is if you walk around where it is meant to be the selection doesn't move)

**Comment by Cekis** [comment]
ok, will check it out and let you know if I need more info on it.

**Comment by Cekis** [comment]
These terminals are supposed to be inside the structure, in one of the main rooms.  I'm testing out a solution now.

**Comment by Cekis** [comment]
Appears the latest commit fixes the issue.  Make sure to rebuild your TAB's (ant compile_tab) and restart your server.
