### ISSUE TITLE
Vehicle customization kits fail

### ISSUE THREAD

**Issue by RaiRaiTheRaichu** [SWG-Source/dsrc#76]
Using a vehicle customization kit on any vehicle results in the string "You have failed customization operations on ..." after applying the changes. Selecting colors in the palette correctly shows the colors changing on the vehicle as a preview, but apply results in the colors reverting with the error message.

Tested with every vehicle available in the frog menu.

Error string is "prose_fail", used in vehicle_base.java.

**Comment by Namsemag** [comment]
Tested with a Crafted V-35 & Crafted Customisation Kits and confirmed as not working

**Comment by Cekis** [comment]
Related to issue #22

**Comment by IrishDarkshadow** [comment]
Fixed by updates to the ACM process and the latest ACM file pushed to the client-assets repo.
