### ISSUE TITLE
Stupid Vents! quest issuw

### ISSUE THREAD

**Issue by lordbogit** [SWG-Source/dsrc#81]
unable to progress the quest due to vents cannot be clicked

**Comment by IrishDarkshadow** [comment]
What quest? what vents? 
No screenshot, no reproduction steps, no info on server version, no info on client version used? no info on if the server & client are patched to the current version via Git. 

In this state, this bug report is about as useful as an ashtray on a motorbike.

**Comment by lordbogit** [comment]
the quest is called stupid vents 
![vent](https://user-images.githubusercontent.com/353448/74686106-5f283100-51c8-11ea-97f3-71dc09c55b42.png)
its just the one

**Comment by Cekis** [comment]
The screenshot helps immensely.  Can somebody verify this is an issue on their builds?  I'll see if I can't reproduce it when I get a chance as well.

**Comment by Cekis** [comment]
@lordbogit can you please test if this is still an issue after you've updated with @BloodCommando 's fixes?

**Comment by lordbogit** [comment]
i have done that a fue weeks back the fix worked no other problems in that theamepark main story
