### ISSUE TITLE
GCW Static Bases on Talus, Naboo and Corellia don't keep their status over server restarts

### ISSUE THREAD

**Issue by nifenap** [SWG-Source/dsrc#83]
GCW static bases on Talus, Naboo and Corellia don't keep their status and timers when a server restart happens. 

When server starts fresh, the three mentioned bases don't belong to any faction and no NPC (as well as factional decoration like flags) are around. You capture all 4 terminals and the base flips to your faction (working as intended). Factional NPC as well as decoration spawns. Also the timer for stims and such starts running. 

If a server restart occurs, the base is reset to neutral with no NPC and factional decoration. It does not matter if you shut down the server gracefully via the /server shutdown command or via ant stop in the console. Also, the time since the base was captured doesn't matter. I captured all bases yesterday and let the server run 'til today - bases were neutral after a restart again. 

Ways to reproduce: 
Start server (mine was from a fresh cloned repo), create a character, join a faction (rebel or imperial - both factions have that issue for me), flip the base. Wait until the server database is saved again (should be 10 MInutes or so?), restart the server. Base should be "neutral" again.

**Comment by Cekis** [comment]
To fix this for a live server situation, just persist the 3 controllers for the static bases (one on Corellia, one on Talus and one on Naboo).  Look for the objects in the buildout files that have this script attached to them:  systems.gcw.static_base.master

They're likely really close to the bases themselves.
