### ISSUE TITLE
GU 16.0 - imp command hat needs species restrictions added

### ISSUE THREAD

**Issue by IrishDarkshadow** [SWG-Source/dsrc#85]
GCW
	Domestics Draft Schematic Added: Imperial Command Hat
	Imperial Command Hat is a wearable for only humans.

**Comment by Namsemag** [comment]
Also needs description changed as it mentions "some humanoid species"

**Comment by Cekis** [comment]
Not a bug.  An image from live indicates this note is not correct.  
![image](https://user-images.githubusercontent.com/3135506/97826731-3b821980-1c77-11eb-88c4-8abb04f29ed6.png)
