### ISSUE TITLE
WoD - Rubina conversation options not working

### ISSUE THREAD

**Issue by lordbogit** [SWG-Source/dsrc#87]
there is a missing script in the convosation 
click "you have not shown support for either Clan" and you get 
![image](https://user-images.githubusercontent.com/353448/79012454-38e69800-7b5e-11ea-8eae-32583007fd05.png)
and another https://www.twitch.tv/videos/588404615

**Comment by Namsemag** [comment]
All of the conversation strings etc are wrong for this character, if you read through all of the chat options its like having multiple personalities, half of the responses are from her perspective
![screenShot0013](https://user-images.githubusercontent.com/55237094/79016932-122d5f00-7b68-11ea-8bd2-afa8e4bbdfac.jpg)
![screenShot0014](https://user-images.githubusercontent.com/55237094/79016943-18234000-7b68-11ea-88cb-2da9186935b1.jpg)

**Comment by xerroth** [comment]
It would seem you need to dl the current strings. There work for me.

**Comment by lordbogit** [comment]
this is on the QA server with client irish gave us

**Comment by Bandit42** [comment]
When turning in the quest Walkabout, Initial convo shows a string. Pic provided

![screenShot0022](https://user-images.githubusercontent.com/35357152/79465683-8a54b400-7fb0-11ea-8f4f-e81bb329a269.jpg)

**Comment by IrishDarkshadow** [comment]
Known issue. Every NPC in WoD has had the conversation strings they were using removed.

Lockhart is currently working on changing the java that drives those conversation options to match the text strings from the final day client.

**Comment by Bandit42** [comment]
okie dokie
