### ISSUE TITLE
WoD Robina Silver SMC NPCs

### ISSUE THREAD

**Issue by Bandit42** [SWG-Source/dsrc#99]
As I approached Robina, I noticed that she has 3 Silver Claw Elites around her. As I recall from Live, this was not the case. Pic Provided
![screenShot0021](https://user-images.githubusercontent.com/35357152/79399744-027f9300-7f39-11ea-8767-3fbcf92e006f.jpg)

**Comment by IrishDarkshadow** [comment]
They were being added by the POI spawner right beside the Rubina NPC. They have now been removed after verifying with a video of that site during live that showed no NPCs surrounding Rubina.
